### ISSUE TITLE
how to fix "use of closed network connection"?

### ISSUE THREAD

**Issue by huangzhong** [XDagger/xmrig2xdag#25]
[XDAG_PROXY] 2022/05/17 02:20:13 Broadcasting new job to connected workers.
[XDAG_PROXY] 2022/05/17 02:20:13 Conn Stop()...ConnID =  4
[XDAG_PROXY] 2022/05/17 02:20:13 read msg head error  read tcp 172.31.44.240:57990->136.243.71.148:13654: use of closed network connection
[XDAG_PROXY] 2022/05/17 02:20:13 136.243.71.148:13654 [conn Reader exit!]
[XDAG_PROXY] 2022/05/17 02:20:13 136.243.71.148:13654 [conn Writer exit!]
[XDAG_PROXY] 2022/05/17 02:20:13 proxy [4] shutdown

**Comment by swordlet** [comment]
pool closed  your proxy's connection

**Comment by swordlet** [comment]
maybe your miner did not commit shares for a long time
