### ISSUE TITLE
./xmrig2xdag: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found 

### ISSUE THREAD

**Issue by seblezinzin** [XDagger/xmrig2xdag#34]
I downloaded last version on github.

All dependecies are ok.
apt-get update upgrade done....
Ubuntu 20.04.4 LTS
this is when I run proxy.
Also : ./xmrig2xdag: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

**Comment by TTJASS** [comment]
I have also encountered this problem

**Comment by swordlet** [comment]
under clib folder
$ cmake .
$ make
build your own clib , proxy will use your own glibc

**Comment by FSOL06** [comment]
@swordlet @Sofarlemineur Should be close now.

**Comment by seblezinzin** [comment]
in reality, last ubuntu 22.04 doesn't include glibc_2.36, we have to upgrade distibution to 22.10 to get 2.36

**Comment by FSOL06** [comment]
@seblezinzin Other case, if you must stay on Ubuntu 22.04, you'll havee to compile it yourself : 

Same process as official XMRIG, except github sources: 

1. sudo apt-get install git build-essential cmake automake libtool autoconf
2. git clone --branch xdag https://github.com/swordlet/xmrig.git
3. mkdir xmrig/build && cd xmrig/scripts
4. ./build_deps.sh && cd ../build
5. cmake .. -DXMRIG_DEPS=scripts/deps
6. make -j$(nproc)

Please find attach files I get after compilation.
[linux_22.04-rig_no_fee_v6.18.0.zip](https://github.com/XDagger/xmrig2xdag/files/10322277/linux_22.04-rig_no_fee_v6.18.0.zip)
