### ISSUE TITLE
XMRIG 6.18 / Dev fees 

### ISSUE THREAD

**Issue by FSOL06** [XDagger/xmrig2xdag#37]
![image](https://user-images.githubusercontent.com/97795464/188261510-74d83008-d7c9-4c2e-9288-8565fd555ea5.png)

Previously, dev fees = 0%.

Please restore this to encourage miner & promote XDAG

**Comment by ldcomcn** [comment]
agree with

**Comment by FSOL06** [comment]
To complete information, here is same screen with XMRIG2XDAG 1.0.6 

![image](https://user-images.githubusercontent.com/97795464/191362973-decfb66a-7232-4b9b-a192-5bf33cdd6c9c.png)

**Comment by FSOL06** [comment]
Done. Not concern proxy but xmrig/swordlet branch xdag.

Close.
