### ISSUE TITLE
SRBMiner connection error

### ISSUE THREAD

**Issue by martin-karailiev** [XDagger/xmrig2xdag#70]
I can't setup SRBMiner to work with xmrig2xdag. I use that command line 

SRBMiner-MULTI.exe --algorithm xdag --pool ******:3232 --wallet G9H9ENvaGrmq3wPU6qt7uEjTzkhZnY2Xq --worker srbminer --cpu-threads 18 --disable-gpu 

Receive these tow errors: 
Socket error: 10054
Pool unexpectedly close the connection

Xmrig2xdag config is:
{
  "strport": 3232,
  "url": "pool.xdag.org:13656",
  "log": "proxy.log",
  "tls": false,
  "debug": false,
  "testnet": false,
  "socks5": "",
  "ratelimit": 10,
  "try_pool_times": 3,
  "try_delay_seconds": 10,
  "exit_on_pool_down": false
}

Any idea why is not working?

**Comment by FSOL-XDAG** [comment]
SRBminer is not designed to work with x2x. It can mine directly on the node without going through a proxy. Only x4x (XMRig-4-XDAG) and XMRig-CC miners need x2x to work.

![image](https://github.com/XDagger/xmrig2xdag/assets/128682335/31903286-c8e2-44a3-81d0-10c97244dee1)

**Comment by martin-karailiev** [comment]
I see. Thanks
